quarkus:
  oidc:
    enabled: false
  oidc-client:
    enabled: false
  otel:
    enabled: false

reqour:
  git:
    git-backends:
      available:
        gitlab:
          url: http://${reqour.git.git-backends.available.gitlab.hostname}:${quarkus.wiremock.devservices.port}

reqour-rest:
  app-environment: test
  reqour-secret-key: test-secret
  indy-url: https://test-indy.example.com

wiremock:
  base-url: http://localhost:${quarkus.wiremock.devservices.port}
