quarkus:
  swagger-ui:
    always-include: true

mp:
  openapi:
    scan:
      exclude:
        classes:
          - org.jboss.pnc.reqour.rest.endpoints.BaseUrlEndpoint

reqour-rest:
  pod-definition-file: 'src/main/resources/pod.yaml'
  app-environment: ${APP_ENV}
  reqour-secret-key: ${REQOUR_SECRET_NAME}
