quarkus:
  swagger-ui:
    always-include: true

mp:
  openapi:
    scan:
      exclude:
        classes:
          - org.jboss.pnc.reqour.rest.endpoints.BaseUrlEndpoint

reqour-rest:
  app-environment: ${APP_ENV}
  reqour-secret-key: ${REQOUR_SECRET_NAME}
  indy-url: ${INDY_URL}
  pod-definition-file-path: 'src/main/resources/pod.yaml' # overridden in runtime config
