quarkus:
  oidc:
    enabled: false
  oidc-client:
    enabled: false
    credentials:
      secret: oidc-client-secret
  otel:
    enabled: false

reqour:
  git:
    git-backends:
      available:
        gitlab:
          url: http://${reqour.git.git-backends.available.gitlab.hostname}:${quarkus.wiremock.devservices.port}
    private-github-user: github-bot

reqour-rest:
  app-environment: test
  reqour-secret-key: test-secret
  indy-url: https://test.indy.com
  sasl-jaas-conf: sasl-jaas-config
  job-definition-file-path: 'src/test/resources/job.yaml'

wiremock:
  base-url: http://localhost:${quarkus.wiremock.devservices.port}
