reqour:
  git:
    git-backends:
      available:
        gitlab:
          git-url-internal-template: git@gitlab.com:workspace
          username: dev-user
      active: gitlab
    acceptable-schemes:
      - https
      - http
      - git
      - git+ssh
      - ssh
