quarkus:
  swagger-ui:
    always-include: true
  log:
    category:
      "org.jboss.pnc":
        level: DEBUG

reqour:
  git:
    git-backends:
      available:
        gitlab:
          git-url-internal-template: git@gitlab.cee.redhat.com:pnc-workspace
          username: user
      active: gitlab
    acceptable-schemes:
      - https
      - http
      - git
      - git+ssh
      - ssh
    private-github-user: ${PRIVATE_GITHUB_USER}
