reqour:
  git:
    git-backends:
      available:
        gitlab:
          hostname: gitlab.com
          username: dev-user
          workspace: dev-workspace
          workspace-id: 1
          token: 'Change me to gitlab group token.'

          protected-tags-pattern: '*'
          protected-tags-accepted-patterns:
          url: http://${reqour.git.git-backends.available.gitlab.hostname}
          git-url-internal-template: git@${reqour.git.git-backends.available.gitlab.hostname}:${reqour.git.git-backends.available.gitlab.workspace}
          read-only-template: http://${reqour.git.git-backends.available.gitlab.hostname}/${reqour.git.git-backends.available.gitlab.workspace}/%s.git
          read-write-template: git@${reqour.git.git-backends.available.gitlab.hostname}:${reqour.git.git-backends.available.gitlab.workspace}/%s.git
      active: gitlab
    acceptable-schemes:
      - https
      - http
      - git
      - git+ssh
      - ssh
