quarkus:
  log:
    console:
      json: false
  oidc-client:
    enabled: false

reqour:
  git:
    git-backends:
      available:
        gitlab:
          hostname: localhost
          username: test-user
          workspace: test-workspace
          workspace-id: 1
          token: I don't even need to be real
          git-url-internal-template: git@localhost:${reqour.git.git-backends.available.gitlab.workspace}
          read-only-template: http://${reqour.git.git-backends.available.gitlab.hostname}/${reqour.git.git-backends.available.gitlab.workspace}/%s.git
          read-write-template: git@${reqour.git.git-backends.available.gitlab.hostname}:${reqour.git.git-backends.available.gitlab.workspace}/%s.git
          protected-tags-pattern: '*'
          protected-tags-accepted-patterns:
      active: gitlab
    acceptable-schemes:
      - https
      - http
      - git
      - git+ssh
      - ssh
    private-github-user: test-bot
    user:
      email: test-user@example.com
      name: ReqourTest
  log:
    final-log:
      bifrost-uploader:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
