quarkus:
  log:
    console:
      json: false
  oidc-client:
    enabled: false

reqour:
  git:
    git-providers:
      gitlab:
        hostname: gitlab.com
        username: dev-user
        workspace: dev-workspace
        workspace-id: 1
        token: 'Change me to gitlab group token.'
        protected-tags-pattern: '*'
        protected-tags-accepted-patterns:
        url: http://${reqour.git.git-providers.gitlab.hostname}
        read-only-template: http://${reqour.git.git-providers.gitlab.hostname}/${reqour.git.git-providers.gitlab.workspace}/%s.git
      github:
        hostname: github.com
        username: dev-user
        workspace: dev-organization
        workspace-id: 1
        token: 'Change me to github token.'
        protected-tags-pattern: '*'
        protected-tags-accepted-patterns:
        url: http://${reqour.git.git-providers.github.hostname}
        read-only-template: http://${reqour.git.git-providers.github.hostname}/${reqour.git.git-providers.github.workspace}/%s.git
      active: github
    acceptable-schemes:
      - https
      - http
      - git
      - git+ssh
      - ssh
    internal-urls:
      - gitlab.com
    user:
      email: dev-user@example.com
      name: ReqourDev
  log:
    final-log:
      bifrost-uploader:
        base-url: http://bifrost.com
