quarkus:
  log:
    category:
      "org.jboss.pnc":
        level: DEBUG
    console:
      format: "%d{HH:mm:ss,SSS} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{3.}] (%t) %s%e mdc:[%X]%n"
    handler:
      kafka:
        enabled: false  # enabled and fully configured in runtime config
        broker-list: kafka.example.com:443
        topic: kafka-topic

reqour:
  git:
    git-providers:
      gitlab:
        url: https://${reqour.git.git-providers.gitlab.hostname}
        git-url-internal-template: "git@${reqour.git.git-providers.gitlab.hostname}:${reqour.git.git-providers.gitlab.workspace}/"
        read-only-template: https://${reqour.git.git-providers.gitlab.hostname}/${reqour.git.git-providers.gitlab.workspace}/%s.git
        read-write-template: git@${reqour.git.git-providers.gitlab.hostname}:${reqour.git.git-providers.gitlab.workspace}/%s.git
        token: ${GITLAB_TOKEN}
      github:
        url: https://${reqour.git.git-providers.github.hostname}
        git-url-internal-template: "git@${reqour.git.git-providers.github.hostname}:"
        read-only-template: https://${reqour.git.git-providers.github.hostname}/${reqour.git.git-providers.github.workspace}/%s.git
        read-write-template: git@${reqour.git.git-providers.github.hostname}:${reqour.git.git-providers.github.workspace}/%s.git
        token: ${GITHUB_TOKEN}
    internal-urls: []  # overridden in runtime config
    private-github-user: ${PRIVATE_GITHUB_USER}
  log:
    final-log:
      bifrost-uploader:
        base-url: ${BIFROST_URL}
      uploader-base-name: 'org.jboss.pnc._userlog_.alignment-log'
    user-log:
      user-logger-name: 'org.jboss.pnc._userlog_.alignment-log'
