quarkus:
  log:
    category:
      "org.jboss.pnc":
        level: DEBUG

reqour:
  git:
    git-backends:
      available:
        gitlab:
          url: https://${reqour.git.git-backends.available.gitlab.hostname}
          git-url-internal-template: git@${reqour.git.git-backends.available.gitlab.hostname}:${reqour.git.git-backends.available.gitlab.workspace}
          read-only-template: https://${reqour.git.git-backends.available.gitlab.hostname}/${reqour.git.git-backends.available.gitlab.workspace}/%s.git
          read-write-template: git@${reqour.git.git-backends.available.gitlab.hostname}:${reqour.git.git-backends.available.gitlab.workspace}/%s.git
          token: ${GITLAB_TOKEN}
    private-github-user: ${PRIVATE_GITHUB_USER}
