reqour-adjuster:
  adjust:
    validate: true
    request: ${ADJUST_REQUEST}
    build-categories:
      STANDARD:
        persistent-mode: PERSISTENT
        temporary-mode: TEMPORARY
        temporary-prefer-persistent-mode: TEMPORARY_PREFER_PERSISTENT
      SERVICE:
        persistent-mode: SERVICE
        temporary-mode: SERVICE_TEMPORARY
        temporary-prefer-persistent-mode: SERVICE_TEMPORARY_PREFER_PERSISTENT
        prefix-of-suffix-version: managedsvc
  maven-executable: mvn
