reqour-adjuster:
  adjust:
    validate: false
    request: |
      {
        "callback": {
          "method": "POST",
          "uri": "https://example.com/callback"
        },
        "originRepoUrl": "git@gitlab.com:repo/project.git",
        "taskId": "task-id",
        "buildType": "MVN",
        "internalUrl": {
          "readwriteUrl": "git@gitlab.com:test-workspace/repo/project.git",
          "readonlyUrl": "https://gitlab.com/test-workspace/repo/project.git"
        }
      }
    mvn:
      cli-jar-path: '/foo/pom-manipulation-cli.jar'
      default-settings-file-path: '/foo/settings.xml'
      temporary-settings-file-path: '/foo/temporary-settings.xml'
      alignment-parameters:
        - '-Dfoo=bar'
    gradle:
      gradle-analyzer-plugin-init-file-path: '/foo/analyzer-init.gradle'
      cli-jar-path: '/foo/gme-cli.jar'
      default-gradle-path: '/usr/share/gradle-42.42.42'
      alignment-parameters:
        - '-Dfoo=bar'
    scala:
      sbt-path: '/usr/bin/sbt'
      alignment-parameters:
        - '-Dfoo=bar'
    npm:
      cli-jar-path: '/foo/project-manipulator-cli.jar'
      alignment-parameters:
        - '-Dfoo=bar'
  mdc: '{}'
